/*
 * Automatically generated by configure - do not modify
 * Configured with: * './configure'
 */
#define CONFIG_32BIT
#define CONFIG_LITTLE_ENDIAN
#define CONFIG_ZLIB
#define CONFIG_FDATASYNC
#define CONFIG_SFAA
#define CONFIG_CLOCK_GETTIME
#define CONFIG_CLOCK_MONOTONIC
#define CONFIG_GETTIMEOFDAY
#define CONFIG_STRSEP
#define CONFIG_STRCASESTR
#define CONFIG_GETOPT_LONG_ONLY
#define CONFIG_INET_ATON
#define CONFIG_SOCKLEN_T
#define CONFIG_TLS_THREAD
#define CONFIG_TCP_NODELAY
#define CONFIG_RLIMIT_MEMLOCK
#define CONFIG_IPV6
#define CONFIG_SETVBUF




